const { SUPABASE_URL, SUPABASE_KEY } = window.APP_CONFIG;
const db = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
const $ = (id) => document.getElementById(id);
let candidates = [];
let lists = [];
let voteToken = sessionStorage.getItem('vote_token') || null;
let participantReferralCode = sessionStorage.getItem('participant_ref') || new URLSearchParams(location.search).get('ref') || null;
let mayorChoice = null, councilListChoice = null, councilChoice = null, currentStep = 1;
let currentProfile = null;
const BLANK = { id: null, blank: true, name: 'Voto en blanco' };
function showToast(message){const el=$('toast');if(!el)return;el.textContent=message;el.classList.remove('hidden');clearTimeout(showToast._t);showToast._t=setTimeout(()=>el.classList.add('hidden'),3200)}
function initials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'?'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function pct(v){return Number(v||0).toFixed(1).replace('.0','')+'%'}
function setView(name){$('publicView').classList.toggle('hidden',name!=='public');$('authView').classList.toggle('hidden',name!=='auth');$('dashboardView').classList.toggle('hidden',name!=='dashboard')}
function textColor(hex){const c=(hex||'#64748b').replace('#','');if(c.length!==6)return'#fff';const r=parseInt(c.slice(0,2),16),g=parseInt(c.slice(2,4),16),b=parseInt(c.slice(4,6),16);return((r*299+g*587+b*114)/1000)>160?'#111':'#fff'}
function normalizePhotoUrl(url){if(!url)return'';if(/^https?:\/\//i.test(url))return url;if(url.startsWith('assets/'))return`./${url}`;if(url.startsWith('/'))return`.${url}`;return url}
function imageMarkup(c,size='large'){const url=normalizePhotoUrl(c?.photo_url||'');const cls=size==='small'?'avatarFallback smallAvatar':'avatarFallback largeAvatar';if(url){return`<img src="${esc(url)}" alt="${esc(c.name||'')}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="${cls}" style="display:none">${initials(c?.name||'')}</div>`}return`<div class="${cls}">${initials(c?.name||'')}</div>`}
function saveReferralCode(code){participantReferralCode=code||null;if(participantReferralCode)sessionStorage.setItem('participant_ref',participantReferralCode);else sessionStorage.removeItem('participant_ref')}
async function loadElectionData(){const [{data:c,error:ce},{data:l,error:le}]=await Promise.all([db.from('vote_candidates').select('*').eq('active',true).order('display_order',{ascending:true}).order('name',{ascending:true}),db.from('vote_lists').select('*').eq('active',true).order('display_order',{ascending:true}).order('list_number',{ascending:true})]);if(ce||le){console.error(ce||le);showToast('No se pudieron cargar los datos electorales.');return false}candidates=c||[];lists=l||[];return true}
async function registerParticipant(){const cedula=$('cedula').value.trim(),gender=$('gender').value,age=$('ageBand').value,residence=$('residence').value.trim();if(!cedula||!gender||!age||!residence){$('registrationMsg').textContent='Completá todos los campos.';return}if(!$('consent').checked){$('registrationMsg').textContent='Necesitás aceptar la participación voluntaria.';return}$('startBtn').disabled=true;$('registrationMsg').textContent='Validando participación…';const {data,error}=await db.rpc('vote_register_participant',{p_cedula:cedula,p_gender:gender,p_age_band:age,p_residence_zone:residence,p_referral_code:participantReferralCode});$('startBtn').disabled=false;if(error){console.error(error);$('registrationMsg').textContent='No pudimos validar los datos. Revisalos e intentá otra vez.';return}if(!data?.ok){$('registrationMsg').textContent=data?.reason==='already_participated'?'Esta cédula ya participó en el simulador.':'No se pudo iniciar la simulación.';return}voteToken=data.token;sessionStorage.setItem('vote_token',voteToken);mayorChoice=null;councilListChoice=null;councilChoice=null;$('registrationCard').classList.add('hidden');$('completedCard').classList.add('hidden');$('ballotSection').classList.remove('hidden');$('cedula').value='';$('registrationMsg').textContent='';await loadElectionData();goStep(1);window.scrollTo({top:$('ballotSection').offsetTop-70,behavior:'smooth'})}
function updateProgress(){document.querySelectorAll('.progressPill').forEach((el,i)=>el.classList.toggle('active',i===currentStep-1))}
function setStepTitles(main,sub){$('ballotStepTitle').textContent=main;$('ballotStepSub').textContent=sub}
function hideAllSteps(){['stepIntendente','stepJuntaList','stepJuntaCandidate','stepSummary'].forEach(id=>$(id).classList.add('hidden'))}
function goStep(step){currentStep=step;hideAllSteps();updateProgress();$('backStepBtn').classList.toggle('hidden',step===1||step===4);$('restartStepBtn').classList.toggle('hidden',step===1||step===4);if(step===1){$('stepIntendente').classList.remove('hidden');setStepTitles('Candidatos a Intendente municipal','Elegí una candidatura o voto en blanco.');renderMayorCards()}else if(step===2){$('stepJuntaList').classList.remove('hidden');setStepTitles('Listas participantes al cargo de Junta municipal','Elegí una lista o voto en blanco.');renderCouncilLists()}else if(step===3){$('stepJuntaCandidate').classList.remove('hidden');setStepTitles('Candidatos a Junta municipal','Elegí una opción de la lista seleccionada.');renderCouncilCandidates()}else{$('stepSummary').classList.remove('hidden');setStepTitles('Opciones seleccionadas','Revisá tus elecciones antes de registrar la simulación.');renderSummary()}}
function mayorCard(c){const bg=c.party_color||'#64748b',fg=textColor(bg);return`<button class="ballotCard bigCard" data-mayor="${c.id}" style="background:${esc(bg)};color:${fg}"><div class="ballotCardHeader"><div class="ballotCardParty">${esc(c.party_name||'')}</div></div><div class="ballotCardBody"><div class="ballotCardPhoto">${imageMarkup(c)}</div><div class="ballotCardMetaBlock"><div class="metaLabel">Lista</div><div class="metaValue">${esc(c.list_number||'')}</div><div class="metaSub">${esc(c.party_abbr||'')}</div></div></div><div class="ballotCardName">${esc(c.name)}</div></button>`}
function renderMayorCards(){const mayors=candidates.filter(c=>c.race_type==='intendente').sort((a,b)=>(a.display_order||0)-(b.display_order||0));$('intendenteGrid').innerHTML=mayors.map(mayorCard).join('')+`<button class="ballotCard blankVote bigCard" data-mayor-blank="1"><div class="blankVoteText">Voto en blanco</div></button>`;document.querySelectorAll('[data-mayor]').forEach(el=>el.addEventListener('click',()=>{mayorChoice=mayors.find(c=>c.id===el.dataset.mayor);goStep(2)}));document.querySelector('[data-mayor-blank]')?.addEventListener('click',()=>{mayorChoice=BLANK;goStep(2)})}
function renderCouncilLists(){$('juntaListGrid').innerHTML=lists.map(l=>{const fg=textColor(l.party_color);return`<button class="ballotCard listCard" data-list="${l.id}" style="background:${esc(l.party_color)};color:${fg}"><div class="listNumber">Lista ${esc(l.list_number)}</div><div class="listParty">${esc(l.party_name)}</div><div class="listAbbr">${esc(l.party_abbr||'')}</div></button>`}).join('')+`<button class="ballotCard blankVote listCard" data-list-blank="1"><div class="blankVoteText">Voto en blanco</div></button>`;document.querySelectorAll('[data-list]').forEach(el=>el.addEventListener('click',()=>{councilListChoice=lists.find(l=>l.id===el.dataset.list);councilChoice=null;goStep(3)}));document.querySelector('[data-list-blank]')?.addEventListener('click',()=>{councilListChoice=BLANK;councilChoice=BLANK;goStep(4)})}
function renderCouncilCandidates(){if(!councilListChoice||councilListChoice.blank){goStep(4);return}const fg=textColor(councilListChoice.party_color);$('juntaListHeading').style.background=councilListChoice.party_color;$('juntaListHeading').style.color=fg;$('juntaListHeading').innerHTML=`<div class="line1">Lista ${esc(councilListChoice.list_number)}</div><div class="line2">${esc(councilListChoice.party_name)}</div>`;const rows=candidates.filter(c=>c.race_type==='junta'&&(c.list_id===councilListChoice.id||c.list_number===councilListChoice.list_number)).sort((a,b)=>(a.option_number||999)-(b.option_number||999));let html=rows.map(c=>`<button class="juntaCandidateCard" data-council="${c.id}"><div class="juntaCandidatePhoto">${imageMarkup(c,'small')}</div><div class="juntaCandidateInfo"><div class="juntaOption">Opción <small>${esc(c.option_number||'')}</small></div><div class="juntaCandidateName">${esc(c.name)}</div></div></button>`).join('');html+=`<button class="juntaCandidateCard voteBlankSmall" data-council-blank="1"><div class="juntaCandidatePhoto"><div class="avatarFallback smallAvatar">—</div></div><div class="juntaCandidateInfo"><div class="juntaOption">Opción <small>—</small></div><div class="juntaCandidateName">Voto en blanco</div></div></button>`;$('juntaCandidateGrid').innerHTML=html;if(!rows.length)showToast('Todavía no hay candidatos cargados para esta lista. Podés volver o elegir voto en blanco.');document.querySelectorAll('[data-council]').forEach(el=>el.addEventListener('click',()=>{councilChoice=rows.find(c=>c.id===el.dataset.council);goStep(4)}));document.querySelector('[data-council-blank]')?.addEventListener('click',()=>{councilChoice=BLANK;goStep(4)})}
function summaryChoiceMarkup(title,choice,listChoice,id){if(!choice||choice.blank)return`<div id="${id}" class="summaryChoice white"><div class="summaryChoiceTitle">${esc(title)}</div><div class="summaryChoiceBody"><div class="blankVoteText">Voto en blanco</div></div><button class="modifyBtn" data-modify="${title.startsWith('Intendente')?'1':'2'}">Modificar</button></div>`;const bg=choice.party_color||listChoice?.party_color||'#64748b',fg=textColor(bg),option=choice.option_number?`<small>Opción ${esc(choice.option_number)}</small>`:'';return`<div id="${id}" class="summaryChoice" style="background:${esc(bg)};color:${fg}"><div class="summaryChoiceTitle">${esc(title)}</div><div class="summaryChoiceBody"><div class="summaryParty">${esc(choice.party_name||listChoice?.party_name||'')}</div><div class="summaryList">Lista ${esc(choice.list_number||listChoice?.list_number||'')}<small>${esc(choice.party_abbr||listChoice?.party_abbr||'')}</small></div><div class="summaryPhoto">${imageMarkup(choice)}</div><div class="summaryName">${esc(choice.name)}${option}</div></div><button class="modifyBtn" data-modify="${title.startsWith('Intendente')?'1':'2'}">Modificar</button></div>`}
function renderSummary(){$('summaryIntendente').outerHTML=summaryChoiceMarkup('Intendente municipal',mayorChoice,null,'summaryIntendente');$('summaryJunta').outerHTML=summaryChoiceMarkup('Junta municipal',councilChoice,councilListChoice,'summaryJunta');document.querySelectorAll('[data-modify="1"]').forEach(b=>b.addEventListener('click',()=>goStep(1)));document.querySelectorAll('[data-modify="2"]').forEach(b=>b.addEventListener('click',()=>goStep(2)))}
function stepBack(){if(currentStep===2)goStep(1);else if(currentStep===3)goStep(2)}
function restartSelection(){mayorChoice=null;councilListChoice=null;councilChoice=null;goStep(1)}
async function submitBallot(){if(!voteToken){showToast('La sesión de participación ya no está disponible.');return}$('submitBallotBtn').disabled=true;const {data,error}=await db.rpc('vote_record_ballot_with_token',{p_token:voteToken,p_mayor_candidate_id:mayorChoice?.blank?null:mayorChoice?.id||null,p_council_candidate_id:councilChoice?.blank?null:councilChoice?.id||null});$('submitBallotBtn').disabled=false;if(error||!data?.ok){console.error(error||data);showToast(data?.reason==='token_used'?'Esta participación ya fue utilizada.':'No se pudo registrar la simulación.');return}sessionStorage.removeItem('vote_token');voteToken=null;$('ballotSection').classList.add('hidden');$('completedCard').classList.remove('hidden');window.scrollTo({top:$('completedCard').offsetTop-90,behavior:'smooth'})}
function resetForNewSimulation(){mayorChoice=null;councilListChoice=null;councilChoice=null;$('completedCard').classList.add('hidden');$('registrationCard').classList.remove('hidden');$('registrationMsg').textContent='';$('gender').value='';$('ageBand').value='';$('residence').value='';$('consent').checked=false;window.scrollTo({top:$('registrationCard').offsetTop-90,behavior:'smooth'})}
async function signUp(){const email=$('email').value.trim(),password=$('password').value;if(!email||password.length<6){$('authMsg').textContent='Ingresá un correo válido y una contraseña de al menos 6 caracteres.';return}const {data,error}=await db.auth.signUp({email,password});if(error){$('authMsg').textContent=error.message;return}if(data.session)await claimRoleAndDashboard();else $('authMsg').textContent='Cuenta creada. Revisá tu correo para confirmar el acceso y luego ingresá.'}
async function signIn(){const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('authMsg').textContent='No se pudo iniciar sesión. Revisá correo y contraseña.';return}await claimRoleAndDashboard()}
async function claimRoleAndDashboard(){let {data:profile}=await db.from('vote_candidate_users').select('role,candidate_id').maybeSingle();if(!profile){const {data:adminClaim}=await db.rpc('vote_claim_first_admin');if(!adminClaim?.ok)await db.rpc('vote_claim_candidate_access');({data:profile}=await db.from('vote_candidate_users').select('role,candidate_id').maybeSingle())}if(!profile){$('authMsg').textContent='Tu cuenta no tiene una candidatura asignada todavía.';return}currentProfile=profile;await loadDashboard(profile)}
async function loadDashboard(profile){setView('dashboard');$('adminPanel').classList.toggle('hidden',profile.role!=='admin');const promises=[db.rpc('vote_my_dashboard'),db.rpc('vote_my_history',{p_days:7}),db.rpc('vote_demographic_summary')];if(profile.role==='candidate')promises.push(db.rpc('vote_candidate_referral_stats'));const results=await Promise.all(promises);const dash=results[0].data,dashErr=results[0].error,hist=results[1].data,demo=results[2].data,referral=profile.role==='candidate'?results[3].data:null;if(dashErr){console.error(dashErr);showToast('No se pudieron cargar las estadísticas.');return}const rows=dash||[];if(profile.role==='candidate'){const r=rows[0]||{};$('statsGrid').innerHTML=statCards([['Intención de voto',pct(r.percentage)],['Simulaciones registradas',r.total_simulations||0],['Registros para tu candidatura',r.candidate_votes||0],['Intención de voto hoy',pct(r.today_percentage)],['Participantes desde tu enlace',referral?.total_participants||0],['Ingresos hoy por tu enlace',referral?.today_participants||0]]);$('dashboardTitle').textContent=r.candidate_name||'Mi panel'}else{const total=rows[0]?.total_simulations||0;$('statsGrid').innerHTML=statCards([['Simulaciones registradas',total],['Candidaturas',rows.length],['Participantes',demo?.total_participants||0]])}if(profile.role==='candidate'){const box=$('candidateLinkBox'),input=$('candidateLinkInput');if(box&&input){const ownCandidate=candidates.find(c=>c.id===profile.candidate_id);const code=ownCandidate?.referral_code||referral?.referral_code;if(code){input.value=`${location.origin}${location.pathname}?ref=${encodeURIComponent(code)}`;box.classList.remove('hidden')}}}renderHistory(hist||[],profile.role);renderDemographics(demo||{});if(profile.role==='admin')await loadAdminCandidates()}
function statCards(items){return items.map(([a,b])=>`<div class="statCard"><div class="statLabel">${esc(a)}</div><div class="statValue">${esc(b)}</div></div>`).join('')}
function renderHistory(rows,role){if(!rows.length){$('history').innerHTML='<div class="empty">Aún no hay datos suficientes.</div>';return}$('history').innerHTML=rows.map(r=>`<div class="historyRow"><div>${new Date(r.day+'T12:00:00').toLocaleDateString('es-PY',{day:'2-digit',month:'short'})}${role==='admin'?`<small><br>${esc(r.candidate_name)}</small>`:''}</div><div class="barTrack"><div class="barFill" style="width:${Math.min(100,Number(r.percentage||0))}%"></div></div><strong>${pct(r.percentage)}</strong></div>`).join('')}
function renderDemographics(demo){const sections=[['Sexo',demo.gender||[]],['Edad',demo.age||[]],['Residencia',demo.residence||[]]];$('demographics').innerHTML=sections.map(([title,rows])=>`<div class="demoSection"><h4>${title}</h4>${rows.length?rows.map(r=>`<div class="demoRow"><div>${esc(r.label)}</div><div class="barTrack"><div class="barFill" style="width:${Math.min(100,Number(r.percentage||0))}%"></div></div><strong>${pct(r.percentage)}</strong></div>`).join(''):'<div class="muted">Sin datos todavía.</div>'}</div>`).join('')}
async function addCandidate(){const name=$('candName').value.trim(),race_type=$('candRace').value,office=$('candOffice').value.trim()||(race_type==='junta'?'Junta municipal':'Intendente municipal'),list=$('candList').value.trim(),party_name=$('candParty').value.trim(),party_abbr=$('candPartyAbbr').value.trim(),party_color=$('candColor').value||'#e11d2f',photo=$('candPhoto').value.trim(),email=$('candEmail').value.trim().toLowerCase(),option_number=$('candOption').value?Number($('candOption').value):null,display_order=$('candOrder').value?Number($('candOrder').value):null;if(!name||!email){$('adminMsg').textContent='Nombre y correo del candidato son obligatorios.';return}$('addCandidateBtn').disabled=true;let listId=null;if(list){const foundList=lists.find(l=>String(l.list_number)===String(list));listId=foundList?.id||null}const payload={name,race_type,office,list_number:list||null,list_id:listId,photo_url:photo||null,party_name:party_name||null,party_abbr:party_abbr||null,party_color,option_number,display_order};const {data:c,error}=await db.from('vote_candidates').insert(payload).select().single();if(error){console.error(error);$('adminMsg').textContent='No se pudo crear la candidatura.';$('addCandidateBtn').disabled=false;return}const {error:ierr}=await db.from('vote_candidate_invites').insert({candidate_id:c.id,email});$('addCandidateBtn').disabled=false;if(ierr){console.error(ierr);$('adminMsg').textContent='Candidatura creada, pero no se pudo registrar el correo de acceso.';return}$('adminMsg').textContent='Candidatura creada correctamente.';['candName','candList','candParty','candPartyAbbr','candPhoto','candEmail','candOption','candOrder'].forEach(id=>$(id).value='');$('candColor').value='#e11d2f';await loadElectionData();await loadAdminCandidates()}
async function loadAdminCandidates(){const {data,error}=await db.from('vote_candidates').select('*').order('race_type',{ascending:true}).order('list_number',{ascending:true}).order('option_number',{ascending:true}).order('name',{ascending:true});if(error){console.error(error);$('adminCandidates').innerHTML='<div class="empty">No se pudieron cargar las candidaturas.</div>';return}$('adminCandidates').innerHTML=(data||[]).map(c=>{const shareUrl=c.referral_code?`${location.origin}${location.pathname}?ref=${encodeURIComponent(c.referral_code)}`:'';return`<div class="adminRow"><div><strong>${esc(c.name)}</strong><div class="adminMeta">${esc(c.race_type||'')} · ${esc(c.office||'')}${c.list_number?` · Lista ${esc(c.list_number)}`:''}${c.option_number?` · Opción ${esc(c.option_number)}`:''} · ${c.active?'Activo':'Inactivo'}</div>${shareUrl?`<div class="adminMeta smallLink">${esc(shareUrl)}</div>`:''}</div><button class="btn ${c.active?'danger':'secondary'}" data-toggle="${c.id}" data-active="${c.active}">${c.active?'Desactivar':'Activar'}</button></div>`}).join('')||'<div class="empty">Sin candidaturas.</div>';document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>toggleCandidate(b.dataset.toggle,b.dataset.active==='true')))}
async function toggleCandidate(id,isActive){const {error}=await db.from('vote_candidates').update({active:!isActive,updated_at:new Date().toISOString()}).eq('id',id);if(error){console.error(error);showToast('No se pudo actualizar la candidatura.');return}await loadElectionData();await loadAdminCandidates()}
function bindEvents(){$('startBtn')?.addEventListener('click',registerParticipant);$('loginBtn')?.addEventListener('click',()=>{setView('auth');$('authMsg').textContent=''});$('cancelAuthBtn')?.addEventListener('click',()=>setView('public'));$('signInBtn')?.addEventListener('click',signIn);$('signUpBtn')?.addEventListener('click',signUp);$('logoutBtn')?.addEventListener('click',async()=>{await db.auth.signOut();currentProfile=null;setView('public')});$('backStepBtn')?.addEventListener('click',stepBack);$('restartStepBtn')?.addEventListener('click',restartSelection);$('restartSelectionBtn')?.addEventListener('click',restartSelection);$('submitBallotBtn')?.addEventListener('click',submitBallot);$('newSimulationBtn')?.addEventListener('click',resetForNewSimulation);$('addCandidateBtn')?.addEventListener('click',addCandidate);$('copyCandidateLinkBtn')?.addEventListener('click',async()=>{const input=$('candidateLinkInput');if(!input?.value)return;try{await navigator.clipboard.writeText(input.value);showToast('Enlace copiado.')}catch{input.select();document.execCommand('copy');showToast('Enlace copiado.')}})}
db.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session)await claimRoleAndDashboard()});
(async()=>{saveReferralCode(participantReferralCode);bindEvents();await loadElectionData();const {data:{session}}=await db.auth.getSession();if(session)await claimRoleAndDashboard()})();
